"""
Django settings for formCreatorApp project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import mongoengine



# -------------------------------
#  BASE CONFIGURATION
# -------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

SECRET_KEY = 'django-insecure-potb@08voa!#63^u#qa0xn9x$!l(01$hs#rmi)%3c66hy$v82u'
DEBUG = True
ALLOWED_HOSTS = []


# -------------------------------
#  APPLICATIONS
# -------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps del proyecto
    'formapp',
    'responseapp',
    'usuarioapp',
    'rest_framework',
    'django_extensions',
    'corsheaders',
    'firebase_auth', 
    'core', # ← 
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #debe ir primero papu
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'formCreatorApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'formCreatorApp.wsgi.application'


# -------------------------------
#  SQLITE DATABASE (por defecto)
# -------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -------------------------------
#  MONGODB CONNECTION
# -------------------------------

mongoengine.connect(
    db='formcreator',
    host='mongodb+srv://juansebastiansari_db_user:AI3v3cYI1ohzxnkp@papucreator.zbmpbf6.mongodb.net/',
    alias='default'
)


# -------------------------------
#  AUTH & SECURITY
# -------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'firebase_auth.authentication.FirebaseAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# -------------------------------
#  INTERNATIONALIZATION
# -------------------------------

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# -------------------------------
#  STATIC & MEDIA FILES
# -------------------------------

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS settings (si usas django-cors-headers)
CORS_ALLOW_ALL_ORIGINS = True  # Solo para desarrollo
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Firebase setting

import firebase_auth.authentication

