"""
Django settings for formCreatorApp project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import mongoengine
from decouple import config



# -------------------------------
#  BASE CONFIGURATION
# -------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

SECRET_KEY = 'django-insecure-potb@08voa!#63^u#qa0xn9x$!l(01$hs#rmi)%3c66hy$v82u'
DEBUG = True
ALLOWED_HOSTS = []


# -------------------------------
#  APPLICATIONS
# -------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps del proyecto
    'formapp',
    'responseapp',
    'usuarioapp',
    'rest_framework',
    'django_extensions',
    'corsheaders',
    'apps.authentication',
    'apps.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ←  Debe ir ANTES de CommonMiddleware papu
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'formCreatorApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'formCreatorApp.wsgi.application'


# -------------------------------
#  SQLITE DATABASE (por defecto)
# -------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -------------------------------
#  MONGODB CONNECTION
# -------------------------------

mongoengine.connect(
    db='formcreator',
    host='mongodb+srv://juansebastiansari_db_user:AI3v3cYI1ohzxnkp@papucreator.zbmpbf6.mongodb.net/',
    alias='default'
)


# -------------------------------
#  AUTH & SECURITY
# -------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# REST Framework configuration
REST_FRAMEWORK = {
    # Configuración de autenticación
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.authentication.firebase_auth.FirebaseAuthentication',  # ← Autenticación personalizada
    ],
    
    # Configuración de permisos por defecto
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Por defecto, endpoints públicos
        # Usa @permission_classes([IsAuthenticated]) en vistas que requieran auth
    ],
    
    # Configuración de respuestas
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # API navegable para desarrollo
    ],
}


# -------------------------------
#  INTERNATIONALIZATION
# -------------------------------

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# -------------------------------
#  STATIC & MEDIA FILES
# -------------------------------

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS settings (si usas django-cors-headers)
CORS_ALLOW_ALL_ORIGINS = True  # Solo para desarrollo
CORS_ALLOW_CREDENTIALS = True

# ===============================================
# INICIALIZACIÓN DE FIREBASE
# ===============================================
# Importar e inicializar Firebase Admin SDK
# DEBE ir al FINAL del archivo settings.py
from apps.core.firebase_config import initialize_firebase

# Inicializar Firebase UNA SOLA VEZ
try:
    initialize_firebase()
    print("✅ Firebase inicializado desde settings.py")
except Exception as e:
    print(f"❌ Error al inicializar Firebase: {e}")
    # En producción, considera lanzar la excepción:
    # raise e

#Settings para Brevo 
BREVO_API_KEY = config('NUEVOBREVO_API_KEY')   #por ahora la dejaré ahí (olvidenlo, ya lo reemplacé, nunca hagan eso que se bloquea)
BREVO_SENDER_NAME = "FormCreator OTP"
BREVO_SENDER_EMAIL = "formcreatorufps@gmail.com"